# Generated by Django 5.2.3 on 2025-06-25 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMTemplate",
            fields=[
                (
                    "llm_template_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("llm_name", models.CharField(max_length=128)),
                ("llm_type", models.CharField(max_length=128)),
                ("llm_template_config", models.JSONField()),
                ("llm_status", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "LLM Template",
                "verbose_name_plural": "LLM Templates",
                "db_table": "llm_templates",
            },
        ),
        migrations.CreateModel(
            name="LLMInstance",
            fields=[
                (
                    "llm_instance_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("llm_config", models.JSONField()),
                ("llm_status", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "llm_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="llm_app.llmtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM Instance",
                "verbose_name_plural": "LLM Instances",
                "db_table": "llm_instances",
            },
        ),
    ]
