# Generated by Django 5.2.3 on 2025-06-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="llmtemplate",
            old_name="llm_name",
            new_name="template_name",
        ),
        migrations.RemoveField(
            model_name="llmtemplate",
            name="llm_type",
        ),
        migrations.AddField(
            model_name="llmtemplate",
            name="template_description",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="llmtemplate",
            name="template_logo",
            field=models.ImageField(blank=True, null=True, upload_to="llm_templates/"),
        ),
        migrations.AlterField(
            model_name="llmtemplate",
            name="llm_template_config",
            field=models.JSONField(
                default=[
                    {
                        "description": "The supplier to use",
                        "key": "supplier",
                        "required": True,
                        "type": "string",
                    },
                    {
                        "description": "The url to use",
                        "key": "url",
                        "required": True,
                        "type": "string",
                    },
                    {
                        "description": "The api key to use",
                        "key": "api_key",
                        "required": False,
                        "type": "string",
                    },
                ]
            ),
        ),
    ]
