# Generated by Django 5.2.3 on 2025-06-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_app", "0002_rename_llm_name_llmtemplate_template_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmtemplate",
            name="template_code",
            field=models.CharField(default="", max_length=10, unique=True),
        ),
    ]
