# Generated by Django 5.2.3 on 2025-06-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_app", "0003_llmtemplate_template_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmtemplate",
            name="llm_template_config",
            field=models.JSONField(
                default=[
                    {
                        "description": "The supplier to use",
                        "key": "supplier",
                        "required": "true",
                        "type": "string",
                    },
                    {
                        "description": "The url to use",
                        "key": "url",
                        "required": "true",
                        "type": "string",
                    },
                    {
                        "description": "The api key to use",
                        "key": "api_key",
                        "required": "false",
                        "type": "string",
                    },
                ]
            ),
        ),
        migrations.AlterField(
            model_name="llmtemplate",
            name="template_code",
            field=models.CharField(default="", max_length=20, unique=True),
        ),
    ]
