# Generated by Django 5.2.3 on 2025-06-27 05:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_app", "0004_alter_llmtemplate_llm_template_config_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="llminstance",
            name="llm_status",
            field=models.CharField(default="ACTIVE", max_length=50),
        ),
        migrations.AlterField(
            model_name="llmtemplate",
            name="llm_template_config",
            field=models.JSONField(
                default='[\n       {\n         "key": "supplier",\n         "type": "string",\n         "description": "The supplier to use",\n         "required": true\n       },\n       {\n         "key": "url",\n         "type": "string",\n         "description": "The url to use",\n         "required": true\n       },\n       {\n         "key": "api_key",\n         "type": "string",\n         "description": "The api key to use",\n         "required": false\n       }\n     ]'
            ),
        ),
        migrations.AlterUniqueTogether(
            name="llminstance",
            unique_together={("llm_template", "created_by")},
        ),
    ]
