# Generated by Django 5.2.3 on 2025-06-27 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_app", "0005_alter_llminstance_llm_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMInstanceLLMModel",
            fields=[
                (
                    "llm_instance_llm_model_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("llm_model_id", models.CharField(max_length=128)),
                ("llm_object_id", models.CharField(max_length=128)),
                ("model_status", models.CharField(default="ACTIVE", max_length=50)),
                ("instance_config", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "llm_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="llm_app.llminstance",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM Instance LLM Model",
                "verbose_name_plural": "LLM Instance LLM Models",
                "db_table": "llm_instance_llm_models",
                "unique_together": {("llm_instance", "llm_model_id")},
            },
        )
    ]
