# Generated by Django 5.2.3 on 2025-06-28 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_app", "0006_llminstancellmmodel_llmmodeluserconfig"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMModelUserConfig",
            fields=[
                (
                    "llm_model_user_config_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("config_type", models.CharField(max_length=128)),
                ("config_value", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "llm_instance_llm_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="llm_app.llminstancellmmodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM Model User Config",
                "verbose_name_plural": "LLM Model User Configs",
                "db_table": "llm_model_user_configs",
                "unique_together": {("config_type", "owner")},
            },
        ),
    ]
