# Generated by Django 5.2.3 on 2025-06-29 06:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("llm_app", "0007_llmmodeluserconfig"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="llminstancellmmodel",
            name="instance_config",
        ),
    ]
