# Generated by Django 5.2.3 on 2025-06-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_app", "0008_remove_llminstancellmmodel_instance_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmmodeluserconfig",
            name="instance_config",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
