# Generated by Django 5.2.3 on 2025-06-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "task_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("task_name", models.CharField(max_length=128)),
                ("task_type", models.CharField(max_length=128)),
                ("task_related_id", models.CharField(max_length=128)),
                ("task_config", models.JSONField()),
                ("task_status", models.CharField(max_length=128)),
                ("task_metadata", models.JSONField()),
                ("task_progress", models.CharField(max_length=128)),
                ("task_progress_msg", models.TextField()),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "db_table": "tasks",
            },
        ),
    ]
