# Generated by Django 5.2.3 on 2025-07-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="created_by",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
