# Generated by Django 5.2.3 on 2025-07-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_app", "0002_task_created_at_task_created_by_task_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_progress",
            field=models.JSONField(),
        ),
    ]
