# Generated by Django 5.2.3 on 2025-07-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_app", "0003_alter_task_task_progress"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="task_progress_msg",
            new_name="message",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="task_config",
            new_name="progress",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="task_status",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="task_metadata",
            new_name="task_data",
        ),
        migrations.RemoveField(
            model_name="task",
            name="task_progress",
        ),
        migrations.AddField(
            model_name="task",
            name="completed_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="error",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="instance_id",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="max_retries",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="task",
            name="retry_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="task",
            name="started_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="timeout",
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_related_id",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
