# Generated by Django 5.2.3 on 2025-07-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_app", "0004_rename_task_progress_msg_task_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="progress",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(default="PENDING", max_length=128),
        ),
    ]
