# Generated by Django 5.2.3 on 2025-06-14 11:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="team",
            field=models.ManyToManyField(
                blank=True, related_name="team_members", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
