# Generated by Django 5.2.3 on 2025-06-13 14:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "document_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_name", models.CharField(max_length=255, null=True)),
                ("document_location", models.CharField(max_length=255, null=True)),
                ("token_num", models.IntegerField()),
                ("chunk_num", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("parser_config", models.JSONField()),
                ("parser_id", models.CharField(max_length=20)),
                ("source_type", models.CharField(max_length=128)),
                ("run_id", models.CharField(max_length=50, null=True)),
                ("status", models.CharField(max_length=50, null=True)),
                ("metadata", models.JSONField(null=True)),
                ("progress", models.CharField(max_length=50)),
                ("progress_msg", models.TextField(null=True)),
                ("progress_begin_at", models.DateTimeField(null=True)),
                ("progress_duration", models.IntegerField(default=0, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "db_table": "documents",
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "document_chunk_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("chunk_location", models.CharField(max_length=255)),
                ("config", models.JSONField()),
                ("status", models.CharField(max_length=255)),
                ("metadata", models.JSONField()),
                ("progress", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rag_app.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Chunk",
                "verbose_name_plural": "Document Chunks",
                "db_table": "document_chunks",
            },
        ),
        migrations.CreateModel(
            name="KnowledgeBase",
            fields=[
                (
                    "knowledge_base_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(null=True)),
                ("document_num", models.IntegerField()),
                ("chunk_num", models.IntegerField()),
                ("permission", models.CharField(max_length=50)),
                ("parser_config", models.JSONField()),
                ("vector_similarity_weight", models.FloatField()),
                ("embed_id", models.CharField(max_length=100)),
                ("language", models.CharField(max_length=50)),
                ("page_rank", models.FloatField(default=0)),
                ("status", models.CharField(default="active", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Base",
                "verbose_name_plural": "Knowledge Bases",
                "db_table": "knowledge_bases",
            },
        ),
        migrations.AddField(
            model_name="document",
            name="knowledge_base",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rag_app.knowledgebase"
            ),
        ),
    ]
