# Generated by Django 5.2.3 on 2025-06-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rag_app", "0002_alter_document_chunk_num_alter_document_token_num_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentchunk",
            name="progress_begin_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="progress_duration",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="progress_msg",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="documentchunk",
            name="progress",
            field=models.CharField(default="INIT", max_length=50),
        ),
    ]
