# Generated by Django 5.2.3 on 2025-06-22 08:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rag_app", "0003_documentchunk_progress_begin_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentchunk",
            name="config",
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "file_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_location", models.CharField(max_length=255)),
                (
                    "file_source",
                    models.CharField(default="local", max_length=255, null=True),
                ),
                ("file_size", models.IntegerField()),
                ("file_type", models.CharField(max_length=255)),
                ("file_status", models.CharField(default="active", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "File",
                "verbose_name_plural": "Files",
                "db_table": "files",
            },
        ),
        migrations.CreateModel(
            name="File2Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rag_app.document",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rag_app.file"
                    ),
                ),
            ],
            options={
                "verbose_name": "File2Document",
                "verbose_name_plural": "File2Documents",
                "db_table": "file_2_documents",
                "unique_together": {("file", "document")},
            },
        ),
    ]
